//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClientConsole.SimpleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.gibe.dk/services", ConfigurationName="SimpleServiceReference.ISimpleService", CallbackContract=typeof(ServiceClientConsole.SimpleServiceReference.ISimpleServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISimpleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gibe.dk/services/ISimpleService/Subscribe", ReplyAction="http://schemas.gibe.dk/services/ISimpleService/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gibe.dk/services/ISimpleService/Subscribe", ReplyAction="http://schemas.gibe.dk/services/ISimpleService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gibe.dk/services/ISimpleService/Unsubscribe", ReplyAction="http://schemas.gibe.dk/services/ISimpleService/UnsubscribeResponse")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gibe.dk/services/ISimpleService/Unsubscribe", ReplyAction="http://schemas.gibe.dk/services/ISimpleService/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gibe.dk/services/ISimpleService/Ping", ReplyAction="http://schemas.gibe.dk/services/ISimpleService/PingResponse")]
        System.DateTime Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.gibe.dk/services/ISimpleService/Ping", ReplyAction="http://schemas.gibe.dk/services/ISimpleService/PingResponse")]
        System.Threading.Tasks.Task<System.DateTime> PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.gibe.dk/services/ISimpleService/StatusUpdated")]
        void StatusUpdated(string args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceChannel : ServiceClientConsole.SimpleServiceReference.ISimpleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleServiceClient : System.ServiceModel.DuplexClientBase<ServiceClientConsole.SimpleServiceReference.ISimpleService>, ServiceClientConsole.SimpleServiceReference.ISimpleService {
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync() {
            return base.Channel.UnsubscribeAsync();
        }
        
        public System.DateTime Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
